### ISSUE TITLE
Cadence extension doesn't launch in v1.4.0

### ISSUE THREAD

**Issue by btspoony** [onflow/vscode-cadence#443]
### Instructions

After upgrading to 1.4.0, the plugin cannot start properly.

### Problem

v1.3.0
<img width="1683" alt="image" src="https://github.com/onflow/vscode-cadence/assets/707025/04302877-5c7e-4029-b077-1460448e57b5">

v1.4.0
<img width="1677" alt="image" src="https://github.com/onflow/vscode-cadence/assets/707025/0f5d823b-c923-4931-9a55-fa281f553a06">

<img width="257" alt="image" src="https://github.com/onflow/vscode-cadence/assets/707025/243eeeb6-02b1-4d4b-92cd-e8a298da77ca">

### Steps to Reproduce

Upgrade into `1.4.0`

### Context

VSCode Version:

版本: 1.82.2 (Universal)
提交: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
日期: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0版本: 1.82.2 (Universal)
提交: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
日期: 2023-09-14T05:59:47.790Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 22.6.0

**Comment by bluesign** [comment]
what is the output of `flow version` ?

**Comment by btspoony** [comment]
> what is the output of `flow version` ?

flow-cli v1.4.5

**Comment by btspoony** [comment]
Update error log in `extension` output

```
2023-10-16 21:37:39.644 [info] ExtensionService#_doActivateExtension onflow.cadence, startup: false, activationEvent: 'onLanguage:cadence'
2023-10-16 21:37:39.750 [error] Activating extension onflow.cadence failed due to an error:
2023-10-16 21:37:39.750 [error] TypeError: Zi.getCurrentHub(...).getScope(...).setPropagationContext is not a function
    at Bwe (/Users/bibi/.vscode/extensions/onflow.cadence-1.4.0/out/extension/src/main.js:71:23753)
    at Object.Fwe (/Users/bibi/.vscode/extensions/onflow.cadence-1.4.0/out/extension/src/main.js:71:22120)
    at iF (/Users/bibi/.vscode/extensions/onflow.cadence-1.4.0/out/extension/src/main.js:106:567)
    at bL (/Users/bibi/.vscode/extensions/onflow.cadence-1.4.0/out/extension/src/main.js:106:2754)
    at zRe (/Users/bibi/.vscode/extensions/onflow.cadence-1.4.0/out/extension/src/main.js:109:7022)

```

**Comment by jribbink** [comment]
hmmm I will take a look at this today and see if I can reproduce it

**Comment by btspoony** [comment]
> hmmm I will take a look at this today and see if I can reproduce it

I suspect it might be related to network loading. 

It was working fine when I was in Vancouver. but after I returned to China, it became broken again.

**Comment by bluesign** [comment]
> It was working fine when I was in Vancouver. but after I returned to China, it became broken again.

I just debugged this; Sentry is blocked in China probably [0] ( Need to handle that on extension ) 

[0] https://forum.sentry.io/t/sentry-in-china/1291/4

**Comment by btspoony** [comment]
It may not be a network issue. I have enabled the global proxy. 
Moreover, according to the reproduction process mentioned above, it is actually possible to start normally.

**Comment by jribbink** [comment]
This looks an awful lot like a sentry bug.  I'm going to make a new release with the latest version of sentry.

see: https://github.com/getsentry/sentry-javascript/issues/8538

**Comment by jribbink** [comment]
@btspoony are you still having this issue on the latest version (v1.4.2)?  I tried to reproduce in v1.4.0 but I wasn't able to.  Let me know if I can close this.

**Comment by btspoony** [comment]
Still there on my machine...
But If you open any CDC file and re-start vscode, the plugin can be launched normally.
```
2023-10-31 11:55:10.082 [info] ExtensionService#_doActivateExtension onflow.cadence, startup: false, activationEvent: 'onLanguage:cadence'
2023-10-31 11:55:10.184 [error] Activating extension onflow.cadence failed due to an error:
2023-10-31 11:55:10.184 [error] TypeError: Ya.getCurrentHub(...).getScope(...).setPropagationContext is not a function
    at KEe (/Users/bibi/.vscode/extensions/onflow.cadence-1.4.2/out/extension/src/main.js:72:23756)
    at Object.WEe (/Users/bibi/.vscode/extensions/onflow.cadence-1.4.2/out/extension/src/main.js:72:22610)
    at NF (/Users/bibi/.vscode/extensions/onflow.cadence-1.4.2/out/extension/src/main.js:106:567)
    at YL (/Users/bibi/.vscode/extensions/onflow.cadence-1.4.2/out/extension/src/main.js:106:2754)
    at eqe (/Users/bibi/.vscode/extensions/onflow.cadence-1.4.2/out/extension/src/main.js:109:7045)
```

**Comment by btspoony** [comment]
It looks normal now.
