### ISSUE TITLE
`textDocument/

### ISSUE THREAD

**Issue by jribbink** [onflow/vscode-cadence#508]
### Problem

`textDocument/documentSymbol` failed error displays any time the LS tries to check this code (i.e. just type in the window and each time it refreshes the LS it will show).

![Screenshot 2024-01-10 at 4 18 50 PM](https://github.com/onflow/vscode-cadence/assets/17958158/d347b6f9-5c33-4b86-8e63-01d7c4a25bc7)

```
[Error - 4:18:09 PM] Request textDocument/documentSymbol failed.
Error: selectionRange must be contained in fullRange
    at Function.validate (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:17337)
    at new d (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:137:17551)
    at kn (/Users/jordan/.vscode/extensions/onflow.cadence-2.2.0/out/extension/src/main.js:77:72602)
    at kn (/Users/jordan/.vscode/extensions/onflow.cadence-2.2.0/out/extension/src/main.js:77:72781)
    at a (/Users/jordan/.vscode/extensions/onflow.cadence-2.2.0/out/extension/src/main.js:77:46794)
    at Object.FMe (/Users/jordan/.vscode/extensions/onflow.cadence-2.2.0/out/extension/src/main.js:77:46880)
    at Object.to [as asDocumentSymbols] (/Users/jordan/.vscode/extensions/onflow.cadence-2.2.0/out/extension/src/main.js:77:72569)
    at l (/Users/jordan/.vscode/extensions/onflow.cadence-2.2.0/out/extension/src/main.js:81:56108)
    at d.provideDocumentSymbols (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:143:39616)
```

### Steps to Reproduce

Write an import similar to what I have and make LS refresh.

### Acceptance Criteria

Doesn't show error.

### Context

Bad UX, useless error

**Comment by turbolent** [comment]
Probably a LS issue, maybe move to the `cadence-tools` repo

**Comment by nichita-rusin** [comment]
Any news on this? It's completely breaking my workflow.
