### ISSUE TITLE
Extension does not activate on Windows 11

### ISSUE THREAD

**Issue by nichita-rusin** [onflow/vscode-cadence#634]
### Environment
* OS: Windiws 11 Pro 23H2
* Cadence: `v0.42.10`
* Flow CLI: `v1.20.4`
* Extension: `v2.3.4`

### Problem

After installing the extension on my Windows 11 machine and rebooting VS Code, it shows as enabled, but does not work. The Extension Host logs have the following error:

```
2024-06-10 12:21:13.329 [error] Activating extension onflow.cadence failed due to an error:
2024-06-10 12:21:13.329 [error] TypeError: Pb.sync is not a function
	at $1 (c:\Users\...\.vscode\extensions\onflow.cadence-2.3.4\out\extension\src\main.js:21:3587)
	at Object.Rie (c:\Users\...\.vscode\extensions\onflow.cadence-2.3.4\out\extension\src\main.js:21:4695)
	at wie (c:\Users\...\.vscode\extensions\onflow.cadence-2.3.4\out\extension\src\main.js:112:8188)
	at async $ie (c:\Users\...\.vscode\extensions\onflow.cadence-2.3.4\out\extension\src\main.js:112:9877)
	at async Cet (c:\Users\...\.vscode\extensions\onflow.cadence-2.3.4\out\extension\src\main.js:140:11526)
	at async a.n (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:6361)
	at async a.m (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:6324)
	at async a.l (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:143:5781)
```

### Steps to Reproduce

No special steps, just installing the extension into VS Code on a Windows machine.

### Acceptance Criteria

The extension works on Windows.

### Investigation

After some digging, I pinpointed the issue to [this call](https://github.com/onflow/vscode-cadence/blob/master/extension/src/telemetry/mixpanel-wrapper.ts#L48) of `osName`. After a lot more digging, I discovered a [breaking issue](https://github.com/sindresorhus/windows-release/issues/33) in the `windows-release` package, which is used by `os-name` internally. I published a PR to fix the issue, meanwhile I think it's best to downgrade `os-name` to v5.1.1, which works properly. Alternatively, it's possible to void the error thrown by `osName()`, but I am not sure how this will affect the telemetry data.

### Context

Flow EVM integration. Not blocking, but really annoying.

**Comment by nichita-rusin** [comment]
Fixing this in #635.
