### ISSUE TITLE
Server crash while accessing variable fields

### ISSUE THREAD

**Issue by MostyXS** [onflow/vscode-cadence#65]
### Problem

Sometimes cadence server just crashing when I starting type something

### Steps to Reproduce

I guess it could be reproduced when you writing variable.{Try random letters, it will happen}

### Context

[Error - 2:37:14 PM] Connection to server got closed. Server will not be restarted.
[Error - 2:37:14 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:29:4057)
	at Object.dispose (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:34:9518)
	at Af.handleConnectionClosed (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:36:9073)
	at Af.handleConnectionClosed (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:39:12267)
	at n (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:36:8755)
	at hu.invoke (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:2:9583)
	at Rr.fire (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:2:10348)
	at ot (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:3:10845)
	at hu.invoke (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:2:9583)
	at Rr.fire (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:2:10348)
	at Po.fireClose (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:2:12622)
	at Socket.<anonymous> (/home/mostyxs/.vscode/extensions/dapperlabs.cadence-0.6.1/out/main.js:2:14174)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)

**Comment by peter064226** [comment]
same issue : Connection got disposed

**Comment by turbolent** [comment]
@MostyXS @peter064226 Would you be able to share the code and actions you tried to perform when you observe the crash?

**Comment by siddthesquid** [comment]
@turbolent Hey, I've been running into the same issues for a little while. 

Here are some more (verbose) logs: https://gist.github.com/siddthesquid/dac81e701f0855e96fb9102a386ebdc2

```
$ flow version
Version: v0.33.0
Commit: d4ae23176dbb8890547bcb98ceaf19f15fc04bf2
```

I only ever see this break on transactions and scripts. Here is one example of how I can reproduce the break - I have the following transaction

```
transaction() {
  prepare(greeter: AuthAccount) {
  }
}
```

Now, if I type in "greeter.s", the server breaks on that last 's'.

```
transaction() {
  prepare(greeter: AuthAccount) {
    greeter.s
  }
}
```

**Comment by siddthesquid** [comment]
I don't think this is an issue anymore by the way. The server has not crashed for me ever after a lot of Cadence
